build_platform: { osx_arm64: osx_64 }
conda_forge_output_validation: true
test_on_native_only: true
provider:
  win: github_actions
  osx: github_actions
  linux: github_actions
channels:
  targets:
    - - napari
upload_on_branch: master
remote_ci_setup: ["conda-forge-ci-setup=3", "py-lief<0.12", "pluggy>=1"]
